### ISSUE TITLE
Job board

### ISSUE THREAD

**Issue by TerraSkye** [samdark/yii-jobs#4]
I like it how you are setting things up of u want to discuss things about job boards let me know. Ive build several of them based on yii amd solr also i might have some ideas of expanding project

**Comment by samdark** [comment]
The project is a bit postponed (till Yii 2.0 is stable). All that I have in mind for now is listed in https://github.com/samdark/yii-jobs/blob/master/todo.md. If you have anything to add, please pull request or write here in comments.

**Comment by arslan-butt** [comment]
Yii 2 is stable now:) could you update it to Yii 2

**Comment by samdark** [comment]
Later. Busy with Yii 2.0.14...

**Comment by arslan-butt** [comment]
Thanks.
